tags:
  - name: diary
    description: diary API

paths:
  # [POST] diaries
  /diaries:
    post:
      tags:
        - diary
      summary: Create a new diary
      parameters:
        - name: body
          in: body
          description: diary content
          required: true
          schema:
            $ref: '#/definitions/CreateDiary'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

    # [GET] diaries
    get:
      tags:
        - diary
      summary: Get all diaries
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  # [GET] diaries/insights
  /diaries/insights:
    get:
      tags:
        - diary
      summary: Get diary insights and trends
      description: Get analytical insights including stress trends, diary counts, and analysis statistics over the past 30 days
      responses:
        200:
          description: 'OK'
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/DiaryInsight'
              message:
                type: string
                example: 'insights'
        500:
          description: 'Server Error'

  # [GET] diaries/id
  /diaries/{id}:
    get:
      tags:
        - diary
      summary: Get diary by ID
      parameters:
        - name: id
          in: path
          description: Diary ID
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        404:
          description: 'Diary not found'
        500:
          description: 'Server Error'

    # [DELETE] diaries/id
    delete:
      tags:
        - diary
      summary: Delete diary by ID
      parameters:
        - name: id
          in: path
          description: Diary ID
          required: true
          type: integer
      responses:
        200:
          description: 'Deleted'
        404:
          description: 'Diary not found'
        500:
          description: 'Server Error'

  # [POST] diaries/id/analyze
  /diaries/{id}/analyze:
    post:
      tags:
        - diary
      summary: Analyze diary content
      parameters:
        - name: id
          in: path
          description: Diary ID
          required: true
          type: integer
      responses:
        200:
          description: 'Analyzed'
        404:
          description: 'Diary not found'
        500:
          description: 'Server Error'

  # [GET] diaries/id/analysis
  /diaries/{id}/analysis:
    get:
      tags:
        - diary
      summary: Get diary analysis
      parameters:
        - name: id
          in: path
          description: Diary ID
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        404:
          description: 'Analysis not found'
        500:
          description: 'Server Error'

# definitions
definitions:
  CreateDiary:
    type: object
    required:
      - content
    properties:
      content:
        type: string
        description: diary content

  Diary:
    type: object
    properties:
      id:
        type: integer
        description: diary ID
      content:
        type: string
        description: diary content
      created_at:
        type: string
        format: date-time
        description: creation timestamp
      status:
        type: string
        enum: [draft, analyzing, analyzed]
        description: diary status

  DiaryAnalysis:
    type: object
    properties:
      id:
        type: integer
        description: analysis ID
      diary_id:
        type: integer
        description: diary ID
      stress_score:
        type: integer
        minimum: 1
        maximum: 5
        description: stress level score
      stress_explanation:
        type: string
        description: stress level explanation
      emotion_category:
        type: string
        description: emotional category
      emotion_words:
        type: array
        items:
          type: string
        description: emotion words
      emotion_intensity:
        type: string
        description: emotion intensity level
      gratitude:
        type: array
        items:
          type: string
        description: gratitude list
      themes:
        type: array
        items:
          type: string
        description: recurring themes
      positive_negative_ratio:
        type: string
        description: positive/negative ratio
      summary:
        type: string
        description: diary summary
      feedback:
        type: string
        description: AI feedback
      model_version:
        type: string
        description: AI model version
      created_at:
        type: string
        format: date-time
        description: analysis creation timestamp

  DiaryInsight:
    type: object
    properties:
      day:
        type: string
        format: date
        description: Date in YYYY-MM-DD format
      avg_stress_score:
        type: number
        nullable: true
        minimum: 1
        maximum: 5
        description: Average stress score for the day (null if no analyses)
      diary_count:
        type: integer
        description: Number of diary entries created on this day
      analysis_count:
        type: integer
        description: Number of analyses completed on this day

schemes:
  - https
  - http
